/**
 * Mock Exam Types
 * Premium 5-credit feature for comprehensive exam preparation
 */

/**
 * Multiple Choice Question for Mock Exams
 */
export interface MCQQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  sourceDocument: string;  // Which PDF it came from
  topic: string;
  difficulty: "easy" | "medium" | "hard";
}

/**
 * Essay Question with grading rubric
 */
export interface EssayQuestion {
  id: number;
  question: string;
  expectedLength: "short" | "medium" | "long";
  rubric: EssayRubric;
  sampleAnswer: string;
  sourceDocuments: string[];
  maxPoints: number;
  suggestedMinutes: number;  // Time allocation
}

/**
 * Grading rubric for essay questions
 */
export interface EssayRubric {
  criteria: RubricCriterion[];
  totalPoints: number;
}

/**
 * Individual grading criterion
 */
export interface RubricCriterion {
  name: string;           // e.g., "Content Accuracy"
  description: string;
  maxPoints: number;
  levels: RubricLevel[];
}

/**
 * Performance levels for grading
 */
export interface RubricLevel {
  score: number;
  label: string;          // e.g., "Excellent", "Good", "Fair", "Poor"
  description: string;
}

/**
 * Complete mock exam content generated by AI
 */
export interface MockExamContent {
  mcqQuestions: MCQQuestion[];      // 30 questions
  essayQuestions: EssayQuestion[];  // 2 questions
  totalTimeMinutes: number;
  generatedAt: string;
  topicsCovered: string[];
}

/**
 * User's essay response
 */
export interface EssayAnswer {
  questionId: number;
  text: string;
  timeSpentMinutes: number;
}

/**
 * Score breakdown for an essay
 */
export interface EssayScore {
  questionId: number;
  criteriaScores: { criterion: string; score: number; feedback: string }[];
  totalScore: number;
  maxScore: number;
  overallFeedback: string;
  timeSpentMinutes: number;
}

/**
 * Comprehensive exam results
 */
export interface MockExamResult {
  mcqScore: number;
  mcqTotal: number;
  essayScores: EssayScore[];
  totalPercentage: number;
  grade: string;
  feedback: ExamFeedback;
  timeSpentMinutes: number;
  topicsStrengths: string[];
  topicsWeaknesses: string[];
}

/**
 * AI-generated feedback for improvement
 */
export interface ExamFeedback {
  strengths: string[];
  areasForImprovement: string[];
  studyRecommendations: string[];
  predictedGrade: string;
  nextSteps: string[];
}

/**
 * Input for generating a mock exam
 */
export interface GenerateMockExamInput {
  documentTexts: { filename: string; text: string }[];
  title?: string;
  difficulty?: "standard" | "challenging";
}

/**
 * Mock exam state in database
 */
export interface MockExam {
  id: string;
  user_id: string;
  title: string;
  source_filenames: string[];
  time_limit_minutes: number;
  mcq_questions: MCQQuestion[];
  essay_questions: EssayQuestion[];
  started_at?: string;
  submitted_at?: string;
  time_spent_seconds?: number;
  mcq_answers?: Record<number, string>;
  essay_answers?: EssayAnswer[];
  mcq_score?: number;
  essay_scores?: EssayScore[];
  total_score?: number;
  feedback?: ExamFeedback;
  status: "draft" | "in_progress" | "submitted" | "graded";
  created_at: string;
}

/**
 * Progress tracking during exam
 */
export interface ExamProgress {
  currentQuestion: number;
  mcqAnswered: number;
  essaysAnswered: number;
  timeRemainingSeconds: number;
  timeSpentSeconds: number;
}

/**
 * Timer warning levels
 */
export type TimerWarning = "normal" | "warning" | "critical" | "expired";

/**
 * Exam section types
 */
export type ExamSection = "mcq" | "essay";

/**
 * Question navigation item
 */
export interface QuestionNavigator {
  id: number;
  type: ExamSection;
  answered: boolean;
  marked?: boolean;
  timeSpentSeconds?: number;
}